### ISSUE TITLE
Improper construction of nested query params

### ISSUE THREAD

**Issue by mdb** [mishk0/slack-bot-api#11]
I am unable to post [attachments](https://api.slack.com/docs/attachments) due to a presumed bug in constructing nested query params.

For example, given the following code:

```javascript
bot.postMessageToChannel('bottest', 'yo!', {
  icon_emoji: ':cat:',
  attachments: [{
    text: 'some text',
    fallback: 'some fallback'
  }]
});
```

A request is performed agains the following path -- note the empty `attachments=`:

```
chat.postMessage?text=yo!&channel=123&username=some_username&icon_emoji=%3Acat%3A&attachments=&token=XXXXXX
```

I believe this is due to a bug within the `querystring` NPM module's `stringify` method.

Please correct me if I am mistaken in my expectations -- I did notice that the following appears to work.

```javascript
bot.postMessageToChannel('bottest', 'yo!', {
  icon_emoji: ':cat:',
  attachments: JSON.stringify([{
    text: 'some text',
    fallback: 'some fallback'
  }])
});
```

Thanks!

**Comment by mishk0** [comment]
Actually, `attachments` should contain a JSON-encoded array, you can find it [here](https://api.slack.com/methods/chat.postMessage).
We have already discussed it https://github.com/mishk0/slack-bot-api/issues/6. I will add this information in REDME.md
