### ISSUE TITLE
Websocket not opened error

### ISSUE THREAD

**Issue by pchodak** [mishk0/slack-bot-api#119]
Appearance |  From time to time
Version | v1.2.0

 
> client_1  | /src/node_modules/slackbots/node_modules/ws/lib/WebSocket.js:219
> client_1  |     else throw new Error('not opened');
> client_1  |          ^
> client_1  | 
> client_1  | Error: not opened
> client_1  |     at WebSocket.send (/src/node_modules/slackbots/node_modules/ws/lib/WebSocket.js:219:16)
> client_1  |     at Timeout._onTimeout (/src/node_modules/ws-heartbeat/client.js:19:12)
> client_1  |     at ontimeout (timers.js:475:11)
> client_1  |     at tryOnTimeout (timers.js:310:5)
> client_1  |     at Timer.listOnTimeout (timers.js:270:5)

**Comment by chrisjoshuamartin** [comment]
@pchodak did you find a solution for this? Seeing this occasionally too.

**Comment by pchodak** [comment]
@chrisjoshuamartin nope i left this project. 
In fact i didn't check if there was some internet connection problem during night on my machine. I recommend to check it, cause I didn't make any try catch for no connection.
