### ISSUE TITLE
Send an image?

### ISSUE THREAD

**Issue by BatDev0** [mishk0/slack-bot-api#144]
Hi!

I just started using this for my slack bot. I would like to make a command that will get a picture from this api https://picsum.photos/. And then sends it the general channel.

I have been looking around for the anwser, if anyone could help that would be a huge help!

**Comment by Matzielab** [comment]
See this issue, it should help out. https://github.com/mishk0/slack-bot-api/issues/10

**Comment by BatDev0** [comment]
Close please
