### ISSUE TITLE
Slack rtm.start() deprecation 

### ISSUE THREAD

**Issue by bathsundeep** [mishk0/slack-bot-api#155]
Hello all, 
Slack recently published a page explaining that they are deprecating `rtm.start()` functionality this month, September 2022, in favor of `rtm.connect()`. 
https://api.slack.com/changelog/2021-10-rtm-start-to-stop

I see that slackbots uses `rtm.start` during `login()` which is called in the constructor of the `Slackbot` class. 
https://github.com/mishk0/slack-bot-api/blob/master/index.js#L33
```
    /**
     * Starts a Real Time Messaging API session
     */
     login() {
         this._api('rtm.start').then((data) => {
             this.wsUrl = data.url;
             this.self = data.self;
             this.team = data.team;
             this.channels = data.channels;
             this.users = data.users;
             this.ims = data.ims;
             this.groups = data.groups;

             this.emit('start');

             this.connect();
         }).fail((data) => {
             this.emit('error', new Error(data.error ? data.error : data));
         }).done();
    }
```

If nothing is done by September 20, this login function will likely break, along with any bots that use this library. This call needs to be replaced with `rtm.connect` and the data returned will also have to change to reflect the new methods return structure.

**Comment by primaryobjects** [comment]
Replacing `rtm.start` with `rtm.connect` successfully allows connecting and listening to events.

However, the subsequent methods getChannels(), getUser(), postMessage(), etc., appear to continue to fail.

As a workaround, you can use the Slack web api to send messages. For example:

```js
const { WebClient, LogLevel } = require('@slack/web-api');

const bot = new SlackBot({ token: token, name: 'MyBot' });
bot.on('message', onMessage);

function onMessage(data) {
  if (data.type == 'message' && data.text && data.subtype != 'bot_message') {
    const client = new WebClient(token, {
      logLevel: LogLevel.ERROR
  });

    const result = await client.chat.postMessage({
      channel: 'general',
      text: 'Hello World'
    });
  }
}
```

**Comment by mishk0** [comment]
thanks for reporting an issue. I've updated deprecated methods. All  these functions `getChannels(), getUser(), postMessage()` should start working now. Thanks!
