### ISSUE TITLE
Slack's update in `connect.start` API breaks the `slackbots` package

### ISSUE THREAD

**Issue by Sundarasan** [mishk0/slack-bot-api#156]
### Issue:
```javascript
const bot = new Slackbot({
  token: 'xxxxx',
  name: 'xxxxx'
})

bot.on('start', () => {
  console.log('Bot channels:', bot.channels)
})
```

**Output is,**
```
Bot channels: undefined
```

### Reason:
- Slack has updated their `connect.start` API method's response which causes the above issue.
- Please refer Slack's [connect.start doc](https://api.slack.com/methods/rtm.start#markdown) to know about deprecation and change in response structure of `connect.start` API.

### Solution:
- `slackbots` package must be updated to adopt to the API response change.

**Comment by mishk0** [comment]
thanks for reporting an issue. I've updated deprecated methods. And please use `getChannels` method in order to get a list of channels, since it's not provided on init anymore. Thanks!
