### ISSUE TITLE
Updating Message

### ISSUE THREAD

**Issue by MTRNord** [mishk0/slack-bot-api#26]
It would be nice if there would be a function to update the last send message. 
So if I get an user request the bot send first "Fetching xy" and than change it to "Fetched xy".

Is this already planned?

**Comment by mishk0** [comment]
It's not planned yet. But if it's interesting, you can try a PR

**Comment by mishk0** [comment]
this is what you are looking for? https://github.com/mishk0/slack-bot-api/pull/41

**Comment by MTRNord** [comment]
I mean what is discribed in https://core.telegram.org/bots/api#updating-messages I am not sure if this is what the function in #41 does.

**Comment by mishk0** [comment]
This functionality was implemented here https://github.com/mishk0/slack-bot-api/pull/41
