### ISSUE TITLE
Bot is typing

### ISSUE THREAD

**Issue by andreafalzetti** [mishk0/slack-bot-api#29]
I was trying to send [this](https://api.slack.com/events/user_typing) event via the RTM API but without any luck.

```
Bot.prototype.botTyping = function(id, params) {
    params = extend({
        type: 'user_typing',
        channel: id,
        user: this.self.id
    }, params || {});

    return this._api('chat.postMessage', params);
};
```

@mishk0 can you see an easy way to add this to this package?
Thanks

**Comment by andreafalzetti** [comment]
@mishk0 I have managed to find a way thanks to 

```
/**
 * Sends an event like Bot is typing to other clients
 * @param {string} id - channel ID
 * @returns {vow.Promise}
 */
Bot.prototype.botTyping = function(channelId) {
  return this.ws.send(JSON.stringify({ type: 'typing', channel: channelId }));
};
``` 

Would you consider adding this feature? I can make a pull request.

**Comment by mishk0** [comment]
Nice, thanks. I would

**Comment by mishk0** [comment]
Sorry, I think, that method is redundant. We can just add this way in the documentation.

**Comment by jehy** [comment]
Still nothing about typing notifications in documentation :(
