### ISSUE TITLE
Get user functionality

### ISSUE THREAD

**Issue by dannysmc95** [mishk0/slack-bot-api#31]
Okay so it's great what this API allows you to do, but one of the main useful things that doesn't seem to be included is actually having a way to convert channel and user IDs back to actual names...? Using DS935739 as a name is not particularly helpful? Is there a way of actually fixing this so I can get users names when they send a message?

**Comment by andreafalzetti** [comment]
Hi there, I had the same thought when I had a deeper look under the hood I figured out that we already have all these informations in the `self` property.

For example I'm doing this:

```
var PlannerBot = function Constructor(settings) {
.........
    this.slack.members = new Array();
.........
};

PlannerBot.prototype._onStart = function () {
    var self = this;
    self._loadBotUser();

    // I retrieve all the users part of the team
    var users = self.getUsers();    
    if(typeof users !== "undefined" &&
       typeof users._value !== "undefined" && 
       typeof users._value.members !== "undefined") {
       users._value.members.forEach(function(user, index) {

        var first_name = "";
        if(typeof user.profile.first_name !== "undefined") {
          first_name = user.profile.first_name;
        }
        self.slack.members[user.id] = {"username" : user.name, "first_name": first_name};
        console.log(user.name.white.bold + " [" + first_name.yellow + "]");
        if(user.name === self.settings.name) {
          self.botID = user.id;
        }
       });
    }
};
```

This is partial code from my application. If you need further help, I'll try to be more explicit.

If it helps, I have used [this](https://scotch.io/tutorials/building-a-slack-bot-with-node-js-and-chuck-norris-super-powers) approach to use this library, which I think it's really a great way!

**Comment by mishk0** [comment]
Actually, you can get all users data from a `users` field or by calling `getUsers` method:
```
bot.on('message', function() {
    var users = bot.users
})
// or

var users = bot.getUsers().then(function(users) { console.log(users) })
```
There is no special method for converting, I will think about it

**Comment by Nicolazinho** [comment]
Here is my solution:
```
var name;
bot.getUsers().then(function(users) {
  for (var eachuser in users.members) {
    if (users.members[eachuser].id == data.user) {
      name = users.members[eachuser].name;
      bot.postMessageToUser(name, 'Hi ' + name, params);
    }
  }
});
```

**Comment by alexellis** [comment]
Could not agree more. It looks useful until you realise how much is missing. Either the documentation needs to reflect this or we need methods to add the functionality. For instance, getChannels does not even contain 1-2-1 messages between bot and user. I've experimented with adding getUserById in my fork. 

https://github.com/mishk0/slack-bot-api/compare/master...alexellis:master
