### ISSUE TITLE
postMessageToChannel not working, callback data is undefined

### ISSUE THREAD

**Issue by Orbyt** [mishk0/slack-bot-api#37]
`data` in the following code is printing out undefined and the bot does not send a new message in Slack. Heres the code: 

```
var self = this;
      self.postMessageToChannel('bottest', 'hi there', {as_user: true}).always(function(data) {
         console.log(' cb = ' + data);
       });
```
Any ideas why? Not sure how to go about debugging it as no errors seem to be thrown.

**EDIT:** So the 'bottest' channel was private, i made a public channel and made the bot respond there and it seems to work. Does this only work on public channels? Is some sort of specific configuration needed to run on private channels?

**Comment by mishk0** [comment]
Is the bot joined to that private channel?

**Comment by mishk0** [comment]
if the error still persists, please, reopen the issue.
