### ISSUE TITLE
Cannot post to a user's slackbot channel

### ISSUE THREAD

**Issue by gpanders** [mishk0/slack-bot-api#45]
Currently, you can only post to a user's DM (IM) channel, but not to their slackbot channel. Add functionality that enables posting to another user's slackbot channel.

Fixed in PR #44

**Comment by robsonbittencourt** [comment]
@mishk0 I think this issue can be closed. The commit 2a6bf412200c2e46b230acf75342fdd08a1fb390 fix it. Right @gpanders ?

**Comment by gpanders** [comment]
Yes @robsonbittencourt. Thanks. Issue is closed.
