### ISSUE TITLE
Error thrown by an inactive account

### ISSUE THREAD

**Issue by lchinitz** [mishk0/slack-bot-api#48]
I've been using slackbots to (successfully) establish connections to applications/bots for which I have the bot token.  However, I just discovered that if the bot is disabled by someone on the team, this causes an error to be thrown by slackbots, and I don't appear to be able to catch it gracefully.  It just crashes.  

Here is a screenshot of the error message;
![image](https://cloud.githubusercontent.com/assets/20801502/17341673/b63460d8-58c3-11e6-9230-8795b559cb27.png)

I tried to just try/catch the var bot = new Slackbot() part of the code, but that's doesn't work.  The error gets thrown anyway and the code crashes.

Is there some clean way of handling this that I'm not seeing?  I don't mind finding out that the account is inactive and then just not connecting to it, but I can't figure out how to do that without crashing the code.

**Comment by vuongtran** [comment]
I got the same issue!

**Comment by mishk0** [comment]
You could subscribe to `error` event and handle error.
```js
bot.on('error', function(data) {
    console.log(data);
});
```
