### ISSUE TITLE
Real life example needed

### ISSUE THREAD

**Issue by ghostsquad** [mishk0/slack-bot-api#5]
I'm a bit new to slack bots, and it seems that I need a better example than what's in the readme. Running this exact code in Nodejs simply starts and immediately stops. It doesn't seem to do anything at all, definitely is not listening for anything.

**Comment by udayms** [comment]
Yeah.. I also feel lost. No idea as to what to do and where to go.

**Comment by mishk0** [comment]
Yes, sure.
Does Node.js throw any error? 
Did you get and specify your own token for the bot?
You get token, when will have created a bot here https://my.slack.com/services/new/bot

**Comment by ghostsquad** [comment]
Yes a have a token. I've abandoned using this framework. Instead I'm using https://github.com/xBytez/slackbotapi now, but also investigating other frameworks.

**Comment by mishk0** [comment]
Anyway, I would glad to know what unclear in example. Could you provide you code? Or it was the same as in readme.md

**Comment by ghostsquad** [comment]
As previously stated, I started with the example code in the readme.

**Comment by alexlrobertson** [comment]
I've tried using the example code as well and I can't get the bot to fire any events. Am I missing an init function for the bot?

**Comment by mishk0** [comment]
@alexlrobertson it didn't throw error in some cases (https://github.com/mishk0/slack-bot-api/commit/20f629648805fc8dd8ca1bad465612ede945f447). Please take index.js from master and try to run this example again. Maybe the reason will become clear.
