### ISSUE TITLE
Log in not working

### ISSUE THREAD

**Issue by llao** [mishk0/slack-bot-api#56]
`Error: SyntaxError: Unexpected token Y in JSON at position 0`
I see this error and I believe it's coming from `Bot.prototype.login` which invokes `this._api('rtm.start')`. Seems the response body isn't being properly parsed.

**Comment by llao** [comment]
Having dived deeper, it looks like my bot hit Slack's rate limit and the response body isn't in JSON, rather it's just a string "Error: You are sending too many requests. Please relax."

**Comment by mishk0** [comment]
this one https://github.com/mishk0/slack-bot-api/issues/57 is similar but with a more suitable title.
