### ISSUE TITLE
string error body (from slack API) breaks JSON.parse

### ISSUE THREAD

**Issue by azazdeaz** [mishk0/slack-bot-api#57]
Hi, 

When slack REST API returns a string as the body, like "You are sending too many requests. Please relax."  (btw. looks like it's enough to send 3-5 messages in a row to get this error...) i get a JSON parse error from [here](https://github.com/mishk0/slack-bot-api/blob/master/index.js#L402)

Thanks for this lib!

**Comment by mishk0** [comment]
would you like to fix it?

**Comment by azazdeaz** [comment]
I would, but what could be a right solution? 
I could wrap the non JSON bodies like this:
```json
{
  ok: false,
  error: body,
}
```
but it seems to be a hacky workaround over a bug in the API

I opened a ticket on the slack-api-docs repo for this: https://github.com/slackhq/slack-api-docs/issues/69

**Comment by mishk0** [comment]
As I can see, anyway, the program doesn't fail. Or you would like to catch a right error message?

**Comment by azazdeaz** [comment]
Well, it throws an unhandled error that breaks the nodejs app. Or how do you mean it "doesn't fail"?

**Comment by mishk0** [comment]
If you get such error in [login()](https://github.com/mishk0/slack-bot-api/blob/master/index.js#L28) method, the program will be finished, because it did't establish websocket connection. You can subscribe on `error` event and process it:

```js
bot.on('error', function(data) {
    setTimeout(() => {
        bot.login();
    }, 1000)
});
```

**Comment by azazdeaz** [comment]
Great, thanks!
