### ISSUE TITLE
Need getUserByEmail method

### ISSUE THREAD

**Issue by mikemcguire** [mishk0/slack-bot-api#58]
I have a use case for getUserByEmail, some of the other node base slackbot apps have this method, but I like yours better and decided to add my own method and have a fork for the time being. I add lodash so I didn't want to send a PR as it seems your intent is to avoid the overhead. 
https://github.com/mikemcguire/slack-bot-api

This is really helpful where an employee of an organisation might be uniquely identified in multiple services by their email rather than their name. For example if someone were to @mention someone on github and you wanted your slackbot to message the same person in your slackteam with the same email.

**Comment by mishk0** [comment]
implemented https://github.com/mishk0/slack-bot-api/commit/d4c7ae7f750807f7aef7350cb0b703bb3d4302a7
