### ISSUE TITLE
Attachments not working

### ISSUE THREAD

**Issue by jpacora** [mishk0/slack-bot-api#6]
The attachments feature (https://api.slack.com/docs/attachments) is not working

**Comment by oscar-b** [comment]
From the Slack docs (https://api.slack.com/rtm):

> The RTM API only supports posting simple messages formatted using our default message formatting mode. It does not support attachments or other message formatting modes.

**Comment by oscar-b** [comment]
Sorry, after diving deeper into this project, I found out that it doesn't use the RTM API at all to send messages, only listen for a handful of events.

The following works for me:

    params.attachments = JSON.stringify(attachment);
    
    bot.postMessage(
    	channel.id,
    	'Hello my friend!',
    	params
    );

**Comment by mishk0** [comment]
Yes, It uses RTM API just for listening incoming events. For sending messages it uses `postMessage` (https://api.slack.com/methods/chat.postMessage) method. There you can find more information about additional params. And for attachments from the [Slack docs] (https://api.slack.com/methods/chat.postMessage):
> The optional attachments argument should contain a JSON-encoded array of attachments. For more information, see the attachments spec.
