### ISSUE TITLE
Allow posting messages to channel ID

### ISSUE THREAD

**Issue by gabmontes** [mishk0/slack-bot-api#60]
The method `postMessageToChannel` accepts channel name but the events like `message` provide only the channel id. It would be great if instead of:

```js
bot.on('message', function ({ channel }) {
  bot.getChannelById(channel)
    .then(({ name }) => bot.postMessageToChannel(name, 'hi!'))
})
```

we could simply do:

```js
bot.on('message', function ({ channel }) {
  bot.postMessageToChannelId(channel, 'hi!') // new method that receives the channel id!
})
```

I would be glad to contribute with a PR!

**Comment by yamikuronue** [comment]
Ah, thank you for opening this issue; I was confused why my code wasn't working. Your workaround is slightly off; you'll want 

```
bot.on('message', function ({ channel }) {
  bot.getChannelById(channel).then((chanInfo) => {
      bot.postMessageToChannel(chanInfo.name, 'hi!');
  });
});
```

**Comment by gabmontes** [comment]
Thanks @yamikuronue! I updated the issue description.

**Comment by mishk0** [comment]
Thanks for reporting this issue. Try to use a `postMessage` method, it gets an ID as a first argument. It's common for posting to channels, users, groups.

**Comment by gabmontes** [comment]
Thanks! Will give it a try.
