### ISSUE TITLE
Bot stop listening events after some time

### ISSUE THREAD

**Issue by lnmunhoz** [mishk0/slack-bot-api#68]
I am running a bot that needs to listen user messages, and it works fine in the first days, but for some reason after a few days the bot stop to listening new messages and I need to restart everything.

Anyone is having this problem? How to avoid that? I am thinking about restart every 24h but this is kind of a workaround on the problem...

**Comment by mishk0** [comment]
Does it throw any errors?

**Comment by imjoshdean** [comment]
I've also noticed this happen. I don't get any errors, myself.

**Comment by lnmunhoz** [comment]
@mishk0 No errors. It just stop listening to channels events.

**Comment by jesuslg123** [comment]
Try running your node.js app with PM2, I had experience this issue but since using PM2, never happen it again... Not sure why.

**Comment by yourfavorite** [comment]
I am experiencing this issue and I am using PM2. I don't seem to find any errors. The bot continues to post messages but does not respond to any messages posted by users. For me I've noticed it after my app has been running for around 40-48 hours though it may happen sooner than this. Is there a good way to get around this issue?

**Comment by haidoan** [comment]
I had same issue and fixed it by 
- install forever in server : npm install forever
- start app : forever start index.js
- list app run by forever : forever list
- kill process : kill -9 XXX (xxx is forever id)
hope it helps.

**Comment by lnmunhoz** [comment]
I solved this issue by switching my server provider. It was hosted on modulus before and now its on heroku and never goes down again.

**Comment by yourfavorite** [comment]
I'm still having this issue on digital ocean. I don't know that it's unique to hosting providers.

**Comment by JacobCooley** [comment]
I'm having this issue on heroku

**Comment by pchodak** [comment]
node_modules/ws/lib/WebSocket.js:219 else throw new Error('not opened');

**Comment by dorman99** [comment]
still having this kind of issue
