### ISSUE TITLE
PostTo remove @ and # of name

### ISSUE THREAD

**Issue by jesuslg123** [mishk0/slack-bot-api#72]
When answering to users or channels, usually from name comes with #channelName or @userName.

On PostTo function, when searching name on the channel, groups and user list, variable name should be cleaned before, removing @ or # on the received name, voiding unnecessary assert.

Something more elegant of this:

     postTo(name, text, params, cb) {
        return Vow.all([this.getChannels(), this.getUsers(), this.getGroups()]).then(function(data) {

            name = name.replace("#", "");
            name = name.replace("@", "");

            var all = [].concat(data[0].channels, data[1].members, data[2].groups);
            var result = _.find(all, {name: name});

            console.assert(result, name, 'wrong name');

            if (result['is_channel']) {
                return this.postMessageToChannel(name, text, params, cb);
            } else if (result['is_group']) {
                return this.postMessageToGroup(name, text, params, cb);
            } else {
                return this.postMessageToUser(name, text, params, cb);
            }
        }.bind(this));
    }

**Comment by jesuslg123** [comment]
Added pull request to address the issue.

https://github.com/mishk0/slack-bot-api/pull/74

**Comment by mishk0** [comment]
PR was merged.
