### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by abhisheksoni27** [mishk0/slack-bot-api#84]
When using `postMessage` to `data.user`, it invokes an infinite loop and keeps sending the same message.

**Comment by bcsjk11** [comment]
I have the same problem :-( Any ideas on this?

**Comment by ibmjm** [comment]
I was getting an infinite loop but it was caused by my posted message (response) containing the same text string that the bot was listening for and responding to.  The bot is listening to all messages including the ones that it sends!

**Comment by Chan9390** [comment]
Yes, @ibmjm is right. I made a bot which replies `I will not help` whenever there's a message which contains `help`. I faced the same issue that the bot is sending the same message (`I will not help`) multiple times and later realized that the bot listens even to the message it sends.

**Comment by eponymz** [comment]
You can avoid this by using this:
```javascript
    // Only read messages that are not other bot messages
    if ((message.subtype && (message.subtype === 'bot_message' || message.subtype === 'message_replied')) || (message.message && message.message.subtype && message.message.subtype === 'bot_message')) {
      return
    }
```

**Comment by duketis** [comment]
> You can avoid this by using this:
> 
> ```js
>     // Only read messages that are not other bot messages
>     if ((message.subtype && (message.subtype === 'bot_message' || message.subtype === 'message_replied')) || (message.message && message.message.subtype && message.message.subtype === 'bot_message')) {
>       return
>     }
> ```
> 
> _EDIT_: ^ that would be in the bot.on('message') handler.

@eponymz  hey mate, I added your code into my message handler but it doesn't seem to work

**Comment by eponymz** [comment]
@duketis that would need to be your first conditional in that handler.

**Comment by duketis** [comment]
`//Message Handler
// Only read messages that are not other bot messages
  if ((message.subtype && (message.subtype === 'bot_message' || message.subtype === 'message_replied')) ||
  (message.message && message.message.subtype && message.message.subtype === 'bot_message')) {
    return
  }

bot.on('message', (data) => {
  if (data.type !== 'message') {
    return;
  }


  handleMessage(data.text);
});`

this is my handler... is this what you are talking about? as I still get an error message saying 'message' is not defined

**Comment by duketis** [comment]
this is my code:

`//Message Handler
// Only read messages that are not other bot messages
if ((message.subtype && (message.subtype === 'bot_message' || message.subtype === 'message_replied')) ||
(message.message && message.message.subtype && message.message.subtype === 'bot_message')) {
return
}

bot.on('message', (data) => {
if (data.type !== 'message') {
return;
}

handleMessage(data.text);
});`

this is my handler... is this what you are talking about? as I still get an error message saying 'message' is not defined
